SpectralPack/Cryptid

Cryptid.lua
Items/Decks.lua

move cry_log_random

---

Items/yM.lua

Fix Fast Food M crash

---

Cryptid.lua
Items/Enhanced.lua

cryptid edition decks

---

Items/zMisc.lua

just update steamodded to latest to fix crash :)

Undo this "patch" as it doesn't make sense in hindsight

---

Cryptid.lua
Items/Enhanced.lua
Items/Spectrals.lua
lovely.toml

currently missing functionality for banana sticker on vouchers, and director's cut/retcon debuffing

changes to editions and sticker decks

---

Cryptid.lua
Items/Blinds.lua
Items/Enhanced.lua
Items/Spectrals.lua
Items/zMisc.lua
Items/zzChallenges.lua
config.lua
lovely.toml
lovely/Stakes.toml
lovely/Sticker.toml

added stickering vouchers and unique sticker functionality for vouchers and consumables

sticker hell

---

config.lua
lovely.toml
lovely/Misc.toml
lovely/Sticker.toml

fix for visibility of rigged and mod badges

temporary hackfix

---

Items/zExotic.lua

Fix Gateway

---

Cryptid.lua
Items/MiscJokers.lua
Items/yM.lua
Items/zMisc.lua
lovely.toml
lovely/Stakes.toml

nothing much
- banana sticker now checks for area (in case of red bloon/food popping before banana check)
- perishable fixed for some reason, even though this shouldn't do anything
- neon m now works properly with double scale
- panopticon :)
- boosters from tags now have editions applied

misc fixes

---

Cryptid.lua
Items/Spectrals.lua
lovely.toml
lovely/Misprint.toml
lovely/Sticker.toml

- voucher debuffing is now not awful
- voucher misprinting now actually exists and isn't broken (changed a few annoyingly hardcoded vouchers too, like antimatter and crystal ball)

voucher misprinting + debuffing

---

Items/MiscJokers.lua

Fix Cursor

---

Cryptid.lua
Items/Spectrals.lua
Items/Stakes.lua
lovely.toml
lovely/Misprint.toml
lovely/Stakes.toml

i slapped some quick and dirty code together... it's not pretty

voucher + pack stickers on stakes

---

Cryptid.lua
Items/CodeCards.lua
lovely.toml
lovely/Sticker.toml

no voucher + pack stickers below yellow stake

---

Cryptid.lua
lovely/Sticker.toml

natural edition fix + set_cost tweaks

---

Cryptid.lua
Items/Stakes.lua

Use https://github.com/Steamopollys/Steamodded/pull/236 generalized ante scaling (also requires https://github.com/MathIsFun0/Talisman/pull/14)
Also changes the steamodded dependency header (note the version format changed to the newly added beta versioning)

stake update ante scaling

---

Items/Decks.lua

pls accept merge it fix big plsssssdasd aws rs

REAL QUICK ENCODED DECK BUGFIX PLS ACCEPT MATH

---

Items/zMisc.lua
lovely/Misc.toml

- Fixed Aura (and other similar objects) not being able to be used

Fixed Aura glitch

---

Items/CodeCards.lua

Rework no longer destroys eternal jokers

---

Cryptid.lua

Use steamodded config properly, actually saves now

---

Cryptid.lua
Items/MiscJokers.lua
Items/zMisc.lua

Reworking these 3 because they are all very weak as uncommons due to their low reliability and consistency of their effects
-Now these 3 jokers are all Common instead of uncommon, with slight tweaks to their pricing after adjusting for editions (see below). 
-In addition they now spawn with their respective edition to provide immediate value in scoring/synergies, but will no longer affect each other
-Typhoon now unselects cards and plays the sound when used like the other seal spectrals do

Meteor Shower, Exoplanet & Stardust rework/balance idk

---

Cryptid.lua
Items/CodeCards.lua
Items/Stakes.lua
Items/zMisc.lua
lovely.toml
lovely/Sticker.toml

requires VERY recent smod update

sticker + seal loc fixes

---

Items/MiscJokers.lua

Add Mario Brothers JokerDisplay

---

lovely/CatMerge.toml

smallest pr ever, adds a cat tag check to one line which shouldn't change anything but will probably prevent problems in the future

safety patch

---

Items/zExotic.lua

scale bignum update

---

Items/zExotic.lua

- Scalae crash fixed
- Scale's end of round effect can now be retriggered

Scalae bug fixes

---

Cryptid.lua
Items/zExotic.lua
lovely/Exponentia.toml

added compatibility to Stella Mortis and Exponentia.

Scalae/ Double Scale added compats

---

Items/Spectrals.lua

That should do it, probably? At least I've tested it a bit.

Fix Summoning

---

Items/zExotic.lua

Fixed Stella Mortis by removeing some parentheses :P

Fixed Stella Mortis by removeing some parentheses :P

---

Cryptid.lua

affected jokers:
- negative joker
- one for all
- tenebris
this was added to the morefluff 1.0.0 port, added here for parity

Allow joker slot increasing jokers to be purchased with full joker slots

---

Items/Misc.lua

replaced the many checks at the top of Misc.lua to decrease repetition

Reformatted Misc.lua

---

Items/MiscJokers.lua
localization/zh_CN.lua

some misc jocker cards cause crash;
like cry-nuts, cry-home etc.

fix some bugs and fix some translation errors

---

localization/fr.lua

The first PR to truly start the French localisation of Cryptid! (and surely not the last)
Au programme:
- Blindes de Boss
- Éditions
- `misc.v_dictionary`
I have already started localising some Jokers, but they aren't yet in this PR, and someone else (ChatSigna on the Discord) has already done Decks.

fr.lua: Boss Blinds, Editions, and a few misc things

---

Items/MiscJokers.lua

- Fixed Nostalgic Invisible Joker being able to copy the 4th sold card

Nostalgic Invis Joker fix

---

localization/de.lua

I made a German Localisation for you

Add German Localisation

---

Items/Vouchers.lua
lovely/Code.toml

Fixes bug, that copy tags don't copy what joker a rework tag has

Copy tag - Rework tag fix

---

Items/Blinds.lua

unfortunately the crash is pretty unpredictable but I haven't had it for a while

possible fix for chip_text_node crashes

---

localization/de.lua
localization/en-us.lua

Adds information to double sided cards, that they can be merged

Update Double-Sided description

---

Items/EpicJokers.lua

Fixes this bug: https://discord.com/channels/1264429948970733782/1301031418691846185 (Double sided Sob creating Negative Obelisk whenever flipped)

Stop infinite Sobelisk

---

localization/fr.lua

french part 5
- The content of the new spooky update! (probably)
- Spectral cards!
- Sleeves!
- a fix for a typo!
now all that's left are vouchers, tags, and packs, i think?

Sleeves, spectrals, and spooks, now in french!

---

localization/de.lua

German localisation for Spooky update

Spooky Localisation

---

localization/fr.lua

the formidiluosus
also adds a fix to the rarities not showing (the keys somehow got fucked up at some point)

Formidiluosus if it was french

---

localization/en-us.lua

Found the wording awkward in my run

Change Phrasing on Haunted House

---

Cryptid.lua

this is a hacky way to do this, but it works for now

fix nil error when possessed on formidiulosus

---

Items/CodeCards.lua
localization/en-us.lua
lovely/Code.toml

"Any played hand is considered to contain a chosen poker hand, resets at end of round"
the big gripe with it is that i want the exploited hand to score cards based on the top result rather than just high card, but should be merge ready? exploit was one of the weaker code cards due to its lack of synergy with "contains" jokers, maybe this'll help it

exploit rework/buff

---

Items/CodeCards.lua
Items/EpicJokers.lua
Items/M.lua
Items/MiscJokers.lua

gotta make sure I didn't mess up syntax or credits lol

WIP remaining Credits

---

Items/MiscJokers.lua
lovely.toml

Forgor to check if the cards are jokers

Necromancer Fix

---

localization/fr.lua

woo! can you believe we're already done?
- Vouchers
- The new hand sizes (not entirely yet)
- the echo card
- Tags
- Everything new since my last PR (Jokers, Planets...)
- Stakes
- The new credit things

French Localization: The Finale

---

localization/fr.lua

that's it, the title says it all

Updated French to latest commits

---

localization/es_ES.lua

also hook's description got too long so it was split

Very spanish typos (and the new hands)

---

localization/es_ES.lua

i remembered what the colour entry on the stakes were for 🎉

Very spanish quips (and also minor corrections)

---

Items/MiscJokers.lua

fix crash with context other in flip side

---

Items/M.lua
Items/MiscJokers.lua
localization/en-us.lua
localization/es_ES.lua
localization/fr.lua
localization/zh_CN.lua

No need to notify the localization teams for this one
(Also due to my VSCode settings it removed some useless whitespaces in the modified files)

Fixed SDM_0 credit typo

---

Items/CodeCards.lua

this is overpowered as all fuck... but it's quite funny
do whatever
probably need to check if editions/enhancements/seals are enabled

pointer playing cards

---

Items/CodeCards.lua

You can now create an Ace using pointer by writing "I", the same way you can write 2 through 10 using II through X. Before, you couldn't.

The Smallest Issue Ever (with pointer making playing cards)

---

Cryptid.lua
Items/CodeCards.lua
Items/Decks.lua

delete on equilibrium and playing cards

---

Cryptid.lua
Items/Vouchers.lua
localization/en-us.lua
lovely/Voucher.toml

adds slightly janky voucher slot system
might need a bit of testing

add "voucher slots", buff multistock

---

Items/CodeCards.lua
Items/EpicJokers.lua
Items/MiscJokers.lua
Items/Vouchers.lua
localization/en-us.lua

Unlocks for some Jokers and Vouchers + english unlock localization

---

Items/MiscJokers.lua

They are fully in More Mario Jokers so we are good to remove them🫡

Ready for Mario and Luigi to go whenever math says

---

Items/CodeCards.lua
localization/zh_CN.lua

localization-zh_CN: improve translations.

support "light" command for code card `class` & update localization

---

localization/zh_TW.lua

Update zh_TW.lua line 1174 j_cry_macabre

---

items/code.lua
items/epic.lua
items/misc_joker.lua

i can't find the gold jonkler limit if there is any

Talisman compat

---

Cryptid.lua
localization/vi.lua

Vietnamese

---

items/blind.lua
items/misc.lua

Old: crashed on hand played
Cause: hand levels are bignum, tried to compare with normal number
fix: make the number a bignum

Major Edition Fixes + Nostalgic Serpent Hotfix

---

items/epic.lua

Fixed One Crash

---

Cryptid.lua

Fixed Another Crash

---

localization/zh_CN.lua

修复部分错误描述；部分描述在含义不变的情况下与官方翻译统一。

localization(zh_CN): update c_cry_analog, j_cry_clicked_cookie, j_cry_candy_dagger

---

items/misc.lua

note: does not trigger on misc. scaling triggers such as crustulum gaining chips from reroll, don't know how to fix and not 100% sure if i should

More Edition Fixes

---

Items/Challenges.lua
localization/vi.lua

A lot of changes were made, but it was for the better good with my own Vietnamese mod.

vi.lua's consistency with VietnameseBalatro

---

Items/Challenges.lua
localization/vi.lua

I'm not really used to opening PRs. Typos can always sneak in without us knowing regardless of how well we try to proofread. I'm opening a draft PR this time to prevent early merges until all prompts are correctly localized.
I'm very sorry about this incident.

Vietnamese typo fixing

---

items/joker_display.lua

https://discord.com/channels/1264429948970733782/1330213401674387466/1338654806876622849 this crash, also probably happens with gold joker, should both be fixed with this

fixed a joker_display.lua crash

---

localization/es_ES.lua

added the unlocks, retranslations, typo fixes and value generalization

es_ES v0.5.3c parity

---

localization/vi.lua

Translate the Exotic cards again to make them even more Exotic.

Retranslate the Exotic cards

---

items/challenge.lua

No More Seraph

---

items/misc.lua
items/misc_joker.lua

(this took 3 attempts to open the PR properly)

Fixed Gold Edition

---

items/misc_joker.lua

`context.other_card` doesn't exist in this, uh, context, so use `context.scoring_hand[X]` instead

Fix Garden of Forking Paths

---

items/exotic.lua

Newcalced Formi

---

items/misc_joker.lua

Before: crashes when seal the deal is disabled
after (hopefully): doesn't crash

Potentially fixed Seal The Deal crash

---

lib/misc.lua

In case of no level data (like with https://discord.com/channels/1264429948970733782/1343413067312009340/1343413067312009340)

Cat Tag Fix

---

localization/fr.lua

This adds mostly everything related to the gameset update.
To any other french people around here, feel free to debate on some translation choices!

Nobody expects the french inquisition

---

localization/vi.lua

Add Jimbo-tron 9000 and LeBaron James

---

lovely/stake.toml

,
https://discord.com/channels/1264429948970733782/1264430590527012924/1344475614857662476

Fixed A Crash

---

items/misc_joker.lua
localization/en-us.lua

https://discord.com/channels/1264429948970733782/1343645567938723840/1344436218313834578

Minor Mask/Broken Mask Loc Fix

---

items/misc_joker.lua

Hunting Season Code

---

items/deck.lua

- Switched from `trigger_effect` to `calculate`
- Fixed some Antimatter Deck effects not applying on the Madness gameset without a Gold Sticker
- Added Code jokers spawn from Encoded Deck to Antimatter Deck
- Added Exotic joker spawn from Wormhole Deck to Antimatter Deck
I didn't add Chocolate Die from Spooky Deck to Antimatter Deck because I'm unsure why it was commented out.

Improved decks

---

localization/en-us.lua

I find myself presently engaged in the deliberate undertaking of this particular action, the reasoning behind which is rooted primarily in the fact that I perceive it to possess an inherently humorous, amusing, and entertaining quality—one that, upon further reflection, consistently evokes within me a profound sense of joy, mirth, and lighthearted amusement. It is, in my estimation, the very nature of this action, in all its intricacies and nuances, that contributes to its comedic appeal, rendering it not only an enjoyable pursuit but one that aligns perfectly with my personal inclination toward humor and lighthearted entertainment. 
Furthermore, the process of engaging in this specific course of action allows me to revel in the sheer absurdity and delightful ridiculousness that I, for …

changed Notebook name to The Motebook

---

items/enhanced.lua
lib/misc.lua
localization/de.lua
lovely/misc.toml

- Added missing use cases for the item deck menu when pressing the "Back" button or "Escape" key
- Fixed a table error in the german translation

Missing item deck menu use cases and german fix

---

items/epic.lua

Sync Catalyst now makes the plasma noise when it balances. (Currently the timing is a little weird and idk how to fix it)

sync catalyst makes plasma noise

---

lib/overrides.lua

Fix display of The Clock when using StrangeLib

---

lovely/lib_misc.toml
lovely/lib_ui.toml

Lets try not to crash when the lovely patches work but Cryptid isn't loaded fully by smods (due to any reason)

Attempt to avoid lovely crashes

---

items/exotic.lua

what https://discord.com/channels/1264429948970733782/1274103559113150629/1348924213913714718 said

Immutable Pi

---

items/epic.lua

https://discord.com/channels/1264429948970733782/1264431244456755283/1349858507532533780

Fixed one thing

---

items/epic.lua
localization/en-us.lua

i did not proofread this, i'm too artbrained atm

Cass's Ticker Fix

---

items/misc.lua

adds obfuscatedtext function to scope and uses to_big() on amount vars

fix noisy planet card crash (aurinko)

---

items/epic.lua

cryptid lore

---

items/code.lua

add some more stand-ins for pointer

---

items/misc_joker.lua
localization/en-us.lua

coded bc i felt like it
https://discord.com/channels/1264429948970733782/1274103559113150629/1351471511923462167
final art: https://discord.com/channels/1264429948970733782/1274103559113150629/1351479917367263312
makes played face cards steel (played not scored so slightly different than midas, but could be changed to do that)

Eye Of Hagane

---

items/achievement.lua
localization/en-us.lua

Discard The Entire Fucking Deck

New Achievement: You're Fucking Kidding/You Can't Be Serious

---

Cryptid.lua
config.lua
localization/en-us.lua
lovely/lib_ui.toml

sorry for the 4 commits I'm on the mobile GitHub ui right now

add "force tooltips" setting 

---

items/exotic.lua

https://discord.com/channels/1264429948970733782/1356798089251524732

fixed thing

---

items/misc.lua

https://discord.com/channels/1264429948970733782/1357101676837867631

fragile fix

---

localization/fr.lua

this should add all the changes since last time I was here

Update french localization

---

items/code.lua
lib/overrides.lua
localization/en-us.lua

: ) would be easy if I I had commit perms

Added credits

---

README.md

Removes references to the Spectral Pack tab and points users to the Thematic Sets.

Bring FAQ up-to-date

---

items/misc_joker.lua
items/spooky.lua

https://discord.com/channels/1264429948970733782/1361786157272137809/1361786157272137809
Crash fix for candy sticks.
I had also encountered an issue involving Jimball not functioning at all, which is down to a variable mistype and no scoring context. I've since changed the title to reflect the new fix on that

Candy Sticks fix + Jimball fix

---

Cryptid.json

at this point it is already, qc + uncompat got merged

version bump

---

items/epic.lua

allows jokers that provide mult or chips to be properly demitriggered

actually use demicolon force-trigger return results

---

items/achievement.lua
localization/en-us.lua

Obtain a Negative Negative Joker.
Idea by playerrWon, approved on CSL by Math

Add Technically Positive (Approved CSL Achievement)

---

items/code.lua

should allow for crossmod to easily detect banishments as well as if anyone wants to use the idea for cryptid stuff later on

add banishing_card context

---

lovely/misc.toml

another annoyance-driven pull request. had to dig into smods for this one. again, have not done much testing but it seems to work.

Fix nostalgic deck retriggers

---

lovely/misprint.toml

so basically if you misprintize the joker by 1x the problem goes away somehow

fix copying jokers with bignum values

---

items/misc.lua
localization/en-us.lua
lovely/abstracted.toml

should put the changes into demicolon branch

Abstract rework

---

localization/fr.lua

Everything new in 0.5.6 has been translated in french, but also:
- Fixed Tropical Smoothie showing a fixed X1.5
- Fixed Scorch's description being untranslated

0.5.6 but french

---

items/spooky.lua
lovely/ccd.toml
lovely/code.toml

fixed:
- ex-ccd cards retaining use button
- multiuse ccd cards going into consumables rather than back into hand
- monopoly money takes all your money if you have a lot of it

various fixes

---

items/code.lua
lib/forcetrigger.lua
lib/overrides.lua
lovely/code.toml

fix function again

---

items/enhanced.lua

to nova: if it ain't broke, don't fix it

fix vanilla jokers not being immutable

---

items/enhanced.lua
items/m.lua
lib/forcetrigger.lua

make hanging chad immutable

---

items/code.lua
items/epic.lua
items/m.lua
items/pointer.lua
lib/forcetrigger.lua
lovely/ccd.toml
lovely/misc.toml

also fix negative consumables not giving consumable slots

fix space joker and burnt joker forcetriggers

---

items/code.lua
lib/forcetrigger.lua
lovely/code.toml

and by fix nperror i mean i basically recoded the entire use function

consumable forcetriggers part 2, and fix nperror

---

items/code.lua
items/spectral.lua
lib/forcetrigger.lua
localization/fr.lua
lovely/misc.toml

also fix a bug where your game would crash if you hovered over Broken Home and your language was set to French

fix remaining consumable forcetrigger crashes

---

items/code.lua
items/misc_joker.lua
items/planet.lua

- banned hooking consumables, since that screws things way up
- make crypto coin give $1-$10 as its text suggests, rather than $0-$9
- fix typo in tefd

more various fixes

---

items/code.lua
items/misc_joker.lua

fix green seal

---

items/misc_joker.lua
localization/en-us.lua

minor changes to yarnball + disabling yarnball

---

lovely/none.toml

i got confused for 20 minutes because apparently it was "NULL" and i was fully convinced NULL was an alias for nil

fix burnt joker crashing if first discard is None

---

items/misc_joker.lua

Simplifies and compacts code for Old Blueprint, uses SMODS.blueprint_effect now

Old Blueprint rewrite

---

items/epic.lua

changed sync catalyst's code to be more up-to-date since balance = true became a thing

sync catalyst update

---

items/misc_joker.lua
items/spooky.lua

fix blacklist and sus crashes and redisable yarnball

---

Cryptid.lua
items/pointer.lua
lib/overrides.lua
lib/pointerlib.lua

fix pointer on tags (plus optimizations!)

---

items/epic.lua

also why does it work like this

fix issue where the card in canvas doesn't have a transform for some reason

---

localization/de.lua

DE: added missing backs and their unlock conditions

DE: added missing backs and their unlock conditions

---

localization/de.lua

should also fix the stylua error

DE: fixed typos

---

localization/de.lua
localization/en-us.lua

added missing strings in "Other" and below; also fixed some typos, again

DE: misc. text

---

items/code.lua

removed an unused variable, simplified the process of selecting which card to be removed, the logic is preserved

"delete" code card clean up

---

localization/fr.lua

new french update!! :D

---

localization/es_ES.lua

Translated both name and descriptions for:
None Jokers (have some doubts about how to properly refer to "None" as a hand on Undefined and Nebulous, would like to change that so I can properly translate it), The, Kitty Printer, High Five, Familiar Currency, Sock and Sock, Broken Home, Jawbreaker, Demicolon and Starfruit (think that's all of them). Fixed some typos here and there.
IMPORTANT
Gave a try at translating abstract cards, if the grammatical order isn't correct let me know, I tried making it sound and read as natural as possible.

Translated some jokers and fixed some typos

---

localization/de.lua

German translation should now be up-to-date again

DE: add all the new stuff

---

items/misc.lua

self-explanatory. should've submitted this earlier though oops

Fix Abstract Card end of round crash

---

lib/overrides.lua

Fixed some crashes related to modded ranks and royal flushes. Seems to work entirely smoothly now

Paved Joker fixes

---

items/m.lua

small fixes to my earlier pr, though somehow using scaling detection has left virgo completely fucked as even with the fix it doesn't increase in value. i honestly think it could be an smods bug as something similar appeared in my own mod that has jokers scale in unusual contexts

partially fix virgo, remove monster hack

---

items/exotic.lua

could use more work before being re-enabled (i'd at least change the description to listed denominator instead of listed odds) but it at least isn't janky as fuck anymore
tatteredlurker's sprite for it is pretty cool if that's needed, though it is also animated
also added myself as a code credit since i basically entirely redid the calculate function from scratch

reimplement (but not re-enable) non verisimile

---

lib/misprintize.lua

mirror manipulate pr i made earlier

---

items/voucher.lua
lovely/code.toml

a possible fix for the satellite uplink voucher. Also the code music is a little inconsistent when finding code cards in celestial packs but ehh its fine. its better than the voucher not working at all.

satellite uplink fix

---

items/exotic.lua

* Caeruleum now hooks SMODS.calculate_individual_effect instead of Card:calculate_joker
* Multiple Caeruleum stacks now work properly with Supercell
* Optimized Caeruleum overall

Fix/optimize Caeruleum
