Items/Blinds.lua

Referencing [this message](https://discord.com/channels/1116389027176787968/1267185254633050153/1267190778669699092).
Added config to The Clock blind to be ignored by Twitch Blinds mod, so it can't appear with zero score.
Obsidian Orb also has this mechanic, but due to it's scaling speed I decide to leave them as it is.

Ignore The Clock by TwitchBlinds mod

---

lovely/Code.toml

Not sure why this wasn't fixed for over a week, it causes a crash. Maybe only for me since I have newer lovely version?

fix space missing between end and return :(

---

Cryptid.lua

Add Steamodded version dependency (moved from `LOADER_VERSION_GEQ` in latest) and ensure Talisman is up to date, so version mismatches show a warning in the mods menu instead of crashing.

More aggressive dependencies

---

Cryptid.lua
Items/Blinds.lua

- fixed editions applying twice very often on edition decks
- fixed disabling sapphire stamp permanently removing card selection limit

literally 2 lines

---

Items/CodeCards.lua

- Fixed "Automaton" having the buttons "buy & use" or "use" available whenever the consumable area was full, leading to no code card spawning afterward.

Fixed "Automaton" ignoring consumable limit

---

Items/MiscJokers.lua
Items/xEpicJokers.lua
Items/zExotic.lua
Items/zM.lua

I haven't tested every single Joker to now if it's doing the right calculation but it at least shouldn't crash in any instance (hopefully)
Some extra fixes:
* It's no longer necessary to manually format Xmult text
* Hand Xmult Jokers check if text is "Unknown" so they don't cheat by looking through facedown cards
* Changed some stuff in the API to make Old Blueprint's display code less clunky
* Bonus Joker count now caps at 2 (as per the ability)
* Added e_mult modifier to the API for Tredecim

Add JokerDisplay joker retrigger functionality + some fixes

---

assets/shaders/astral.fs
assets/shaders/blur.fs
assets/shaders/glitched.fs
assets/shaders/mosaic.fs
assets/shaders/noisy.fs
assets/shaders/oversat.fs

Refactored GLSL code to avoid implicit type conversions between float and int. Explicit type casting has been added to ensure compatibility with strict compilers.

Fix type mismatch errors in shader code

---

Cryptid.lua
lovely/Misprint.toml

the patch overwrites the fields of card.ability, which causes issues with colour cards
removing it (probably) doesn't cause any issues with existing consumeables

Remove buggy patch from Misprint.toml (and fix a crash)

---

Cryptid.lua

I'm not 100% familiar with the codebase, so please double check this. 
After looking at the history and the objects involved, I'm pretty sure center_no was supposed to be used rather than Card.no(), since the tables being fed into this local function aren't cards.

Fix Ace Aequilibrium crash in aeqviable

---

Cryptid.lua

Steel Joker and others use the value set during Card.update(dt) in order to set values used during scoring calculation. If these jokers are created during scoring, update() won't be called in time, and the game will crash due to unset values.
Manually calling update() on the card after spawning it fixes the crash.

Fix crash when spawning steel joker during scoring (Scrabble tile, Ace Aequilibrium)

---

localization/de.lua
localization/en-us.lua

Makes the fact, that on the flip side **_only_** triggers the backside more clear (I saw someone on the discord asking and thought it would be better to clarify)
Also make a post for the localisation on the discord so it can also be done for the other languages.

Update On The Flip Side description

---

Items/EpicJokers.lua

Added a guard wrapper around the calculations on Sync to prevent it from treating normal numbers as omega nums

Prevent Crash on Sync due to invalid hand

---

Items/Sleeves.lua

Fixes the extremely important issue of a minor spelling mistake within the name of a variable, that isn't even visible while playing the game (very important)

Extremely important fix

---

Items/EpicJokers.lua
localization/de.lua
localization/en-us.lua
localization/en_ES.lua
localization/es_419.lua
localization/fr.lua
localization/id.lua
localization/ja.lua
localization/ko.lua
localization/nl.lua
localization/pl.lua
localization/pt_BR.lua
localization/ru.lua
localization/zh_CN.lua
localization/zh_TW.lua

Seems like the new aditions will be adding other
cursed jokers to cryptid so changing sob from
cry_curse to cry_curse_sob will free up the name
and make sob just a tiny bit less cursed in the
code (not that it still isn't)

Changes cry_curse to cry_curse_sob

---

Items/CodeCards.lua

Removed conversion from smods.rarity to number for epic jokers make commit properly give epic jokers

Fix commit giving rares on epic joker commit

---

Cryptid.lua
Items/CodeCards.lua
Items/EpicJokers.lua
Items/Spooky.lua
Items/Tags.lua

adds a function for selecting a food joker that respects the banned cards

Fix: Food joker not checking for ban and sync crash v2?

---

Items/Spooky.lua

Prevents joker effect from permanently persisting after it has been removed

chocolate dice end event on leave deck

---

lovely.toml

The introduction of "realer_card_limit" conflicts with Steammodded's implementation of negative playing cards, resulting in bugs when change_size() is called during a round while negative cards are in hand (for instance, obtaining or selling a joker like Troubador/Merry Andy).
I'm assuming that realer_card_limit was primarily introduced to deal with situations where extreme hand sizes resulted in the cards becoming extremely scrunched up, to the point where they were impossible to click, hence the introduction of realer_card_limit to try and limit the size under normal conditions.
Instead of using realer_card_limit, this change just fixes the cardarea alignment itself to align cards as if the hand size were capped at the deck size.

Remove realer_card_limit (handsize <= decksize limit), fix card spacing instead

---

Items/Misc.lua

The reason for a lot of the major crash reports at the minute was this single line in [Misc]( Items/Misc.lua) that set the base of the back side to nil. I'm sure the was meant to be an "Empty" card made at some point but it's not present and causes double sidded to break everything

Double sided but with out jank

---

Items/MiscJokers.lua
lovely/Misc.toml

this was an easter egg mechanic originally intended by linus, although it's not really a perfect representation of it
should affect commons, uncommons, and rares (this means sources of common/uncommons could spawn blueprints with this active, but not other rarities)
feel free to tweak the numbers around or move it, i was just messing with it
i thought multiplicative growth could be fun since it would be very difficult to proc it, but maybe it's too steep

old bp dying causes blueprint corruption

---

Items/CodeCards.lua

adds checks to see if the jokers are banned/exist
before spawning.
this is in response to jen banning copy paste
and making antimatter crash.

add checks for encoded deck joker spawning

---

Items/Stakes.lua

one line change :skull:
technically the other applied_stakes should be changed to remove the prefix as well, but steamodded recognizes the already present prefix so it's fine

Fix stakes not unlocking

---

Items/CodeCards.lua
lovely/Code.toml

basically this:
- allows opening packs
- refreshes packs when run shop is entered and exited
- when opening arcana/spectral, draws cards from run cardarea (where the hand is stored) and returns them there

open packs in run shop

---

lovely/Code.toml

Removes a debug log that printed every frame. This would fill up DebugPlus's log buffer and make logs dissapear, and also spammed my console and the lovely logs.

misc: don't spam logs

---

localization/zh_CN.lua

"Jolly Joker" is currently translated into two different word in zh_CN: "开心小丑" and "欢乐小丑". This commit aims to unify these translations to ensure consistency

localization-zh_CN: Unify translations for "Jolly Joker" to "欢乐小丑"

---

lovely.toml

Define some commonly used variables and functions using lovely instead of smods to prevent most crashes when cryptid is enabled and talisman is disabled.
This is so users can use the steamodded mods menu to enable or disable talisman or cryptid as they see fit instead of having to go into their mod files.

Attempts to avoid crashes when talisman is disabled

---

Items/MiscJokers.lua

previously the "Compound Interest" joker would cause a crash when balance was a negative number (thanks to credit card). A fringe case, but still not ideal.
Hopefully now it just does nothing, rather than break the game.

fixed compound interest with negative balance PLEASE REVIEW

---

lib/gameset.lua

I hate this so if there's a better solution than this please use that instead

refactor branch: hacky hack to stop modicon crash

---

items/misc_joker.lua

https://discord.com/channels/1264429948970733782/1330213401674387466/1336166657718227025

Small fix for nice joker

---

items/planet.lua

Suit Planet Fixes

---

items/epic.lua

https://discord.com/channels/1264429948970733782/1330213401674387466/1341877393501192287
why was this all together beforehand???

Possibly fixed a Spectrogram Crash

---

lib/gameset.lua

The other line changes are just whitespaces VSCode automatically deletes

Added SDM_0's Stuff to cross mods

---

items/code.lua

Using ://exploit during a code pack opening results in a crash, so this restrict usage to hand selection only

Only allow the use option on ://exploit during hand selection

---

items/misc_joker.lua

Either
Garden of Forking Paths is not supposed to be compatible and _blueprint_compat_ should = false.
or
Garden of Forking Paths is supposed to be compatible and the context checks should not include _and not context.blueprint_

fixed garden of forking paths compatibility with blueprint

---

.gitignore
items/code.lua
items/epic.lua
items/misc.lua
items/misc_joker.lua
lib/ascended.lua
lib/gameset.lua
lib/misc.lua
localization/id.lua
localization/ja.lua
localization/ko.lua
localization/pt_BR.lua
localization/ru.lua
localization/zh_TW.lua

Deals with a bunch of LSP diagnosic warns that wouldn't already be muted (e.x. "redundant-parameter", "ambiguity-1", "missing-fields" etc.). Also adds `.gitignore` for two common ways of setting LSP settings. 
Also has a bugfix for that one whoops I made several months ago that nobody noticed.

Quick LSP Fixes

---

items/enhanced.lua

This PR ensures that when an item deck is selected from the item deck menu, the game returns to the deck selection instead of reopening the menu.
Tested successfully with and without Galdur.

Improved item deck selection

---

Cryptid.lua

Fixed an issue where specific cross-mod items were missing the class prefix at the beginning of their key.

Fixed cross-mod missing class prefix

---

lib/ui.lua

Since SMODS.DrawStep was added and used, Cryptid edition/enhancement/sticker/etc decks in Galdur's new run menu do not show correctly. This PR attempts to band-aid fix that.
Also, the `Card:click` hook at enhanced.lua ([link](https://github.com/MathIsFun0/Cryptid/blob/66767a001d76774bc48b0ef6d7d9b80397c25d48/items/enhanced.lua#L350)) is still broken on the vanilla new run menu when Galdur is present and disabled internally through its own `Galdur.config.use` setting.

Galdur + CardSleeves compat

---

lovely/code.toml

Was previously defined in another `G.FUNCS` function for some reason, instead of globally.
This could apparently crash under very specific circumstances: https://discord.com/channels/1264429948970733782/1264430590527012924/1348097494890053733

Globally define discard_cards_from_highlighted

---

lib/cross-mod.lua

The unique Cryptid modifiers now display in the preview as they do in blind select

Add support for Next Ante Preview

---

items/epic.lua

removed print statement that would send a message everytime scalae/double scale is triggered when debug+ is used (this annoyed me very much)
discord username: MrDingus

Fixed the debug+ spam from scalae/double scale

---

lib/https.lua

This fixes a crash on some weird modded systems (*cough cough* mobile *cough cough*) that don't have a https backend. Untested cause I was too lazy to debug cryptid crashing on my machine.

fix: crash on some weird systems

---

localization/en-us.lua

small change in conduit's localization in order to make it more clear that you cannot use it on _any_ card (ex: consumables)

tiny wording change in conduit

---

lib/content.lua

Added a currently unused (but planned to be used by the wip and unscreened Gemstone content set) way to make enhancements unable to create bulwarks and clusterfucks

not_stoned_or_fucked

---

lib/misc.lua

Crustulum, and I assume other jokers too, would have it's value reach an omega-number ("e###e###"), then the game would crash. 
https://github.com/MathIsFun0/Cryptid/blob/4ebd1d4e5437cbe3708776a0c446cfc4bbd4812f/lib/misc.lua#L186
Attempts to return the number from the vars table. If those numbers are OmegaNums ("e###e###"), to_number will just return the string itself and not an actual number, then later on in the `pluralize` function would try to use this string as an actual number and the game would crash. 
Added:
https://github.com/bobjoe400/Cryptid/blob/831f3ac996c1e106c6b19b76cec77d6d0da4837b/lib/misc.lua#L187
```lua
if type(num) == 'string' then num = (Big and to_number(to_big(num))) or num end
```
To check to see if `num` is a string and if so, attempt to do a big number conversion …

Added check for if to_number returns a string within pluralize. 

---

items/blind.lua
lib/overrides.lua

Rank blinds and Dropshot weren't up to date

Properly use SMODS.has_no_rank and SMODS.has_no_suit instead of explicit check for Stone Cards

---

items/misc_joker.lua

Pot of jokes would continue to store values internally, even though it's displayed as 1000, over 1000 for `extra.h_size` and then crashing the game by passing these into `CardArea:change_size`
Hard clamp the values of `extra.h_size` and `extra.h_mod` to 1000 and 0 when `extra.h_size + extra.h_mod` gets to be equal to or greater than 1000. 
None
`misc.lua`
* Added hardcoded clamping to Pot of Jokes internal values

Fixed Pot of Jokes internally storing values over it's set limit

---

lib/ascended.lua

Similarly to how the sol card works when leveling up ascended hands, The mult and chip colors are eased to gold whenever an ascended hand is played or selected and back to normal otherwise.

Ascended hands turn the mult & chips colours gold

---

items/misc_joker.lua
localization/en-us.lua

Pot of Jokes wasn't applying the full possible handsize if it scaled too quickly
Added tracking for how much hand size we've already added. Using this tracking modified the `calculate` function to check if we've added 1000 hand size by the time that the internal value goes over 1000, if not, add that much to the hand size. 
* Put the tracking values and the maximum added handsize into a newly named "immutable" table. This works with the "immutable"  skip in misprintize (#507). 
* Added flavor text to pot of jokes displaying the maximum added hand size
* Made maximum added hand size an easily changeable value in the `config` table.
None
`items/misc_joker.lua`
* Rework/fix of Pot of Jokes
`localization/en-us.lua`
* Added flavor text for maximum added hand size.

Fix to new Pot of Jokes calculate implementation

---

lib/misprintize.lua

Add "immutable" tables to a card's ability. Allow `misprintize_tbl` to skip over these tables so certain values of a joker aren't modified, resulting in a more granular approach to immutability. 
Added a few lines to `misprintize_tbl` to check if our table name is "immutable", if so, skip that table. 
None
`lib/misprintize.lua`
* Added check for table name of "immutable" within `misprintize_tbl`
This has been tested with the new Pot of Jokes implementation:
* #508

Ability to skip over whole tables in misprintize

---

items/epic.lua

in case of glitched clockwork giving <1 steel xmult bonus

minor clockwork fix

---

items/stake.lua

- Amber stake now has one booster pack in the shop as intended

Fix Amber Stake

---

items/code.lua

should work for consumable sets, joker rarities, and specific keys

use pointerblist

---

lovely/stake.toml

Fixes Crimson Stake by patching game.lua to only restock shop vouchers on even numbered antes

Crimson Stake Patch

---

items/blind.lua

There have been some complaints from how these spawn way too early, so it has been adjusted:
- The Decision will spawn from **Ante 4**
- The Clock will spawn from **Ante 2**
- The Tax will spawn from **Ante 2**
https://discord.com/channels/1264429948970733782/1264431244456755283/1369856059006517248

Make The Decision, Tax and Clock appear in later antes

---

lib/content.lua

make the unique consumable type not show up in the collection since potion is hidden from collection so its useless

---

items/blind.lua
lib/misc.lua
lib/overrides.lua
lovely/blind.toml

https://discord.com/channels/1264429948970733782/1370761753478037574/1370761753478037574
A user has reported a major crossmod issue involving repeatedly drawing the deck and upping the ante, softlocking the game. Turns out fixing the issue involved removing the need for an entire G.STATE for the decision, instead simply invoking cry_before_cash inside end_round(). This should also work with running only base cryptid.
There is also an additional fix for if you have Unpleasant Card or running Polterworx (the former automatically skips, the latter overrides the skip check functionality to always be skippable anytime), where if all jokers are eternal/cursed, it will no longer skip. Expect unpleasant noises if you have the unpleasant card. …

Major crossmod Decision Fix + accounting for Unpleasant Card/Polterworx 

---

items/code.lua
items/stake.lua
lib/overrides.lua
lovely/ccd.toml

fixed:
- perishable consumables being unable to be used, even after using ://PATCH
- negative CCD cards give consumable slots when copied
- Scorch and Nostalgic arm cause obsidian orb to be unwinnable (this doesn't work though, needs further investigation)

various fixes

---

items/code.lua
items/epic.lua
items/pointer.lua
lib/forcetrigger.lua

- demicolon properly displays "Dangerous!" when next to a consumable
- consumables which require selected cards now select random cards to use
- fix boredom crash, again
- add aliases for Nostalgic Googol Play Card, Oil Lamp, and Tropical Smoothie, since people keep trying to make them

make forcetriggering consumables work better, and some fixes

---

items/blind.lua
items/epic.lua
lib/calculate.lua

- supercell no longer crashes with bignums
- vermillion virus properly breaks hooks when it destroys hooked jokers
- rnjoker+scalae is a bit safer now

fix 3 very specific bugs

---

lovely/misc.toml

debuffed negative jokers don't take up space. this makes no sense.

make debuffed negative playing cards not take up space

---

items/code.lua
lib/gameset.lua

Changed the implementation of the ctrl-v code card so it properly interacts with packs. It's also set up to not have issues with other mods that add objects that aren't jokers, consumables, or playing cards.
Also added a little converter to the start of the set_ability hook to ensure it stays compatible with the smods implementation

ctrl-v fix and fixed set_ability crash

---

items/enhanced.lua
lib/misprintize.lua

Centers can now define misprintize_caps as a table which represents a list of values to be capped in the ability table additionally tables like extra in the ability table can also be setup in the misprintize_caps table to be capped for Cryptid for example capping the two values would be like this G.P_CENTERS.c_cryptid.mizprintize_caps = {extra = 50, max_highlighted = 50}
for supercell it would be something like this
misprintize_caps = {extra = {stat1 = 20, stat2 = 20, money = 20}},
in the centers definition

Add value cap list for specific centers to misprintize

---

items/spectral.lua

I am not entirely sure if no one cared enough to fix this or if it is intentional.
Well, if it is fine then we can probably just go ahead and let people unlock this naturally again. 
<details>
<summary>Thank you to all the people who mentioned Typhoon not doing anything (who were very promptly ignored), so that I actually cared enough to add this single line.</summary>
Kelsey
Draggy11
Butterfly
scrimblo
Huitzil37
zach
Pr0z4c
Probe1
T342
_Caketaco_ <- Cake tacos are probably not healthy for you but they are magnificent regardless.
</details>

Enables Typhoon to unlock the coveted Seal Deck [I love seals]

---

items/sleeve.lua

Implemented Antimatter sleeve
Antimatter sleeve will copy the positive effects of any sleeve completed on Gold Stake or Above.
Antimatter sleeve will copy the positive special effects of any sleeve-deck combination if it is being used with either the corresponding deck, or Antimatter Deck IF said deck has been completed on Gold Stake or above.
If the special effect applies, the base effect does not apply. This is consistent with the behavior of all other deck-sleeve combinations. With the sole exception of Balanced Sleeve, I did not add any special effects.
When no special effects exists for using both the deck and the sleeve, I implemented it to just repeat the deck effect twice. The game balance of this decision is dubious.
I implemented Balanced Sleeve to have a special effect when …

Antimatter Sleeve Full Implementation

---

localization/tools/find_missing.py
localization/tools/find_missing_adv.py

I wrote two small python scripts to help find what entries are missing in a given localization file, comparing it to en-us.lua. If you want to, you can use them too!

Tools to help find missing entries in localization files

---

assets/shaders/astral.fs
assets/shaders/blur.fs
assets/shaders/glass.fs
assets/shaders/glitched.fs
assets/shaders/glitched_b.fs
assets/shaders/gold.fs
assets/shaders/m.fs
assets/shaders/mosaic.fs
assets/shaders/noisy.fs
assets/shaders/oversat.fs
assets/shaders/ultrafoil.fs

Prevents the following error (and similar) when attempting to load the mod in mobile.
```
Oops! The game crashed: 
Error validating vertex shader code: 
Line 167: ERROR: '=': cannot convert from 
'const int' to ' temp highp float' 
Line 167: ERROR: ": compilation 
terminated 
ERROR: 2 compilation errors. No code 
generated. 
```

Avoid use of any integer to float coercion in shaders to support mobile

---

items/code.lua

Was just checking this code for reference and realized it was mistakenly credited to Math. I wrote the code for this (https://github.com/SpectralPack/Cryptid/pull/40)

fix: semicolon code

---

items/m.lua

noticed this wasn't done. monster and megg's code are a little sketchy, and i feel like neon m and motebook could potentially receive changes too
the misc changes:
- virgo being reformatted, and its effect properly accounting for its base cost rather than assuming it's equal to its scaling value
- monster functioning with scalae/double scale though the method i used is kinda hacky, feel free to revert this one
- motebook entirely bypassing the probability check when enough jolly jokers are present instead of setting the numerator to 1e20
- tredecim not displaying "M!" messages when copied by blueprint

m joker scaling detection + some other misc changes

---

items/pointer.lua

this fixes the unlock for pointer, which is currently broken as multiple people in the discord server have pointed out
anyways i noticed a lot of unlocks causes the game to become unresponsive while the unlock popup is visible, idk what causes it but that's out of scope for this pr

fix encoded deck unlock

---

lib/content.lua

So, well I did notice that epic jokers just never naturally spawnwed, and looking in the code, I found out why. It's due to it not being updated with the new content set update. Definitely an oversight

Fixed epic jokers not spawning (hopefully). (This is like my first contribution to this project in any form)
